services:
  sahha-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL=https://sahha-now.live/api
    restart: unless-stopped
    container_name: sahha-frontend
    networks:
      - sahha-shared-network

networks:
  sahha-shared-network:
    external: true