services:
  sahha-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL=https://104.248.45.73/api
    restart: unless-stopped
    container_name: sahha-frontend
    networks:
      - sahha-network

networks:
  sahha-network:
    driver: bridge